### ISSUE TITLE
Add more quiz data

### ISSUE THREAD

**Issue by TimA314** [TimA314/dev-training-ground-server#3]
add quiz questions and answers in the quiz json file.

**Comment by ParisaTork** [comment]
Happy to do this for you, if you'd like?

**Comment by TimA314** [comment]
That would be great!

**Comment by ParisaTork** [comment]
Great - I'll sort it out now!

**Comment by ParisaTork** [comment]
Thanks - I've added the PR here: https://github.com/TimA314/dev-training-ground-server/pull/4

**Comment by TimA314** [comment]
> Thanks - I've added the PR here: https://github.com/TimA314/dev-training-ground-server/pull/4

Great job I've accepted the PR and will close this issue
